# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{couchrest_money}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vinicius Teles"]
  s.date = %q{2011-02-17}
  s.description = %q{This gem makes it easier to work with Money in a project that uses CouchRest::Model.}
  s.email = %q{vinicius@improveit.com.br}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "couchrest_money.gemspec",
    "lib/couchrest/core_extensions/integer.rb",
    "lib/couchrest/core_extensions/nil_class.rb",
    "lib/couchrest/core_extensions/numeric.rb",
    "lib/couchrest/core_extensions/string.rb",
    "lib/couchrest/money.rb",
    "lib/couchrest/money/big_decimal_parser.rb",
    "lib/couchrest/money/float_parser.rb",
    "lib/couchrest/money/integer_parser.rb",
    "lib/couchrest/money/string_parser.rb",
    "lib/couchrest/money_validator.rb",
    "lib/couchrest/positive_money.rb",
    "lib/couchrest/positive_money_validator.rb",
    "lib/couchrest_money.rb",
    "spec/couchrest/money_spec.rb",
    "spec/couchrest/positive_money_spec.rb",
    "spec/locales/pt-BR.yml",
    "spec/spec_helper.rb",
    "spec/support/validation.rb"
  ]
  s.homepage = %q{http://github.com/viniciusteles/couchrest_money}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Money class that acts as a Couchrest CastedModel.}
  s.test_files = [
    "spec/couchrest/money_spec.rb",
    "spec/couchrest/positive_money_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/validation.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<couchrest_model>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<couchrest_model>, [">= 1.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
    else
      s.add_dependency(%q<couchrest_model>, ["~> 1.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<couchrest_model>, [">= 1.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<couchrest_model>, ["~> 1.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<couchrest_model>, [">= 1.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.3.0"])
  end
end

